server:
  port: 0

management:
  port: 0

spring:
  cloud:
    stream:
      bindings:
        multiply-input:
          content-type: application/json
          destination: requests
          group: multiply
          consumer:
            concurrency: 10
        multiply-output:
          content-type: application/json
          destination: replies

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
