# ----------------------------------------
# Create:
#   docker stack deploy -c stack.yml demo
# Status:
#   docker stack services demo
# Delete:
#   docker stack rm demo
#
version: '3.1'

services:

  app-server:
    image: gustajz/sb-request-reply-demo:server
    environment:
      RABBITMQ_HOST: rabbitmq
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s  
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M

  app-client:
    image: gustajz/sb-request-reply-demo:client
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
      - 8080:8080
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672