server:
  port: 0

management:
  port: 0

spring:
  cloud:
    stream:
      default:
        content-type: application/json
      bindings:
        multiply-input:
          destination: requests
          group: multiply
          consumer:
            concurrency: 30
        multiply-output:
          destination: replies
      rabbit:
        bindings:
          multiply-input:
            consumer:
              autoBindDlq: true
              prefetch: 50
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
